[package]
name = "basic_window"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
baldr = { path = "../../"}
anyhow = "1.0.52"
cacao = "0.2.1"
